# Выбор базового образа
FROM node:latest

# Создание директории приложения внутри образа
WORKDIR /usr/src/app

# Копирование файлов package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей, включая продакшн-зависимости
RUN npm install --only=production

# Копирование всех файлов проекта в образ
COPY . .

# Открытие порта, который использует приложение
EXPOSE 3000

# Запуск приложения
CMD ["node", "server.js"]
