# Выбор базового образа
FROM node:latest

# Создание директории приложения внутри образа
WORKDIR /usr/src/app

# Копирование файлов package.json
COPY package.json .

# Установка зависимостей
RUN npm install

# Копирование всех файлов проекта в образ
COPY . .

# Открытие порта, который использует приложение
EXPOSE 5000

# Запуск приложения
CMD ["node", "server.js"]