# Выбор базового образа
FROM node:latest

# Создание директории приложения внутри образа
WORKDIR /usr/src/app

# Копирование файлов package.json и package-lock.json
COPY package.json .
COPY package-lock.json .

# Копирование всех файлов проекта в образ
COPY . .

# Установка зависимостей
RUN npm install
RUN npm uninstall bcrypt
RUN npm install bcryptjs
RUN npm install bcrypt
RUN npm install express
RUN npm install morgan
RUN npm install body-parser
RUN npm install mongoose

# Открытие порта, который использует приложение
EXPOSE 5000

# Запуск приложения
CMD ["node", "server.js"]
